In [1]:
import numpy as np
from scipy.ndimage import correlate

input_img = np.arange(25).reshape(5, 5)
print(input_img)

weights = [[0, 1, 0],
		   [1, 2, 1],
		   [0, 1, 0]]

res_img = correlate(input_img, weights)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Exercise 1
Print the value in position (3, 3) in res_img. Explain the value?  
*It corresponds to the value in position (3,3) in res_img, which is the result of: $6*0+7*1+8*0+11*1+12*2+13*1+16*0+17*1+18*0$*

In [2]:
print(res_img[2, 2])

72


## Exercise 2
Compare the output images when using reflection and constant for the border. Where and why do you see the differences.  
*The differences are in the borders of the images. This is because of the mode that is used to correlate the image with the weight.*

In [3]:
res_img_cons = correlate(input_img, weights, mode="constant", cval=10)
res_img_refl = correlate(input_img, weights, mode="reflect", cval=10)
print(res_img_cons)
print(res_img_refl)

[[ 26  20  25  30  40]
 [ 36  36  42  48  54]
 [ 61  66  72  78  79]
 [ 86  96 102 108 104]
 [ 96 110 115 120 110]]
[[  6  11  17  23  28]
 [ 31  36  42  48  53]
 [ 61  66  72  78  83]
 [ 91  96 102 108 113]
 [116 121 127 133 138]]


## Exercise 3
Read and show the image Gaussian.png from the exercise material.
Use correlate with the Gaussian.png image and the mean filter. Show the resulting image together with the input image. What do you observe?

Try to change the size of the filter to 10, 20, 40 etc.. What do you see?

*The image is blurred, as the size is incremented*

What happens to the noise and what happens to the places in image where there are transitions from light to dark areas?

*The change in the brightness of the image decreases*

In [4]:
import cv2 
import math 

def show_in_moved_window(win_name, img, x, y):
    """
    Show an image in a window, where the position of the window can be given
    """
    cv2.namedWindow(win_name)
    cv2.moveWindow(win_name, x, y)
    cv2.imshow(win_name, img)

In [5]:
gaussian = cv2.imread("Gaussian.png", cv2.IMREAD_GRAYSCALE)
show_in_moved_window("Gaussian Image", gaussian, 0, 10)

In [6]:
for s in [5, 10, 20, 40]:
    size = s
    # Two dimensional filter filled with 1
    weights = np.ones([size, size])
    # Normalize weights
    weights = weights / np.sum(weights)
    res_img_gauss = correlate(gaussian, weights)
    pos = int(math.log2(s/5)+1) * 280
    show_in_moved_window('Gaussian Image with Filter {}'.format(size), res_img_gauss, pos, 10)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Exercise 4
Filter the Gaussian.png image with the median filter with different size (5, 10, 20...). What do you observe? What happens with the noise and with the lighth-dark transitions?

In [7]:
from skimage.filters import median

show_in_moved_window("Gaussian Image", gaussian, 0, 10)

for s in [5, 10, 20, 40]:
    size = s
    footprint = np.ones([size, size])
    med_img_gauss = median(gaussian, footprint)
    pos = int(math.log2(s/5)+1) * 280
    show_in_moved_window('Gaussian Image with Filter {}'.format(size), med_img_gauss, pos, 10)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Exercise 5
Try to use your mean and median filter with different filter sizes on the SaltPepper.png. What do you observe? Can they remove the noise and what happens to the image?

In [8]:
saltpepper = cv2.imread("SaltPepper.png", cv2.IMREAD_GRAYSCALE)
show_in_moved_window("SaltPepper Image", gaussian, 0, 10)

for s in [5, 10, 20, 40]:
    size = s
    # Two dimensional filter filled with 1
    weights = np.ones([size, size])
    # Normalize weights
    weights = weights / np.sum(weights)
    res_img = correlate(saltpepper, weights)
    footprint = np.ones([size, size])
    med_img = median(saltpepper, footprint)
    pos = int(math.log2(s/5)+1) * 280
    show_in_moved_window('SaltPepper Image with Mean Filter {}'.format(size), res_img, pos, 10)
    show_in_moved_window('SaltPepper Image with Median Filter {}'.format(size), med_img, pos, 400)
cv2.waitKey(0)
cv2.destroyAllWindows()


## Exercise 6
Let us try the Gaussian filter on the Gaussian.png image. Start by importing the filter.  
Try to change the sigma value and observe the result.

In [9]:
from skimage.filters import gaussian

img_org = cv2.imread("Gaussian.png", cv2.IMREAD_GRAYSCALE)

sigma = 5
gauss_img = gaussian(img_org, sigma)

show_in_moved_window("Gaussian Image with Gaussian Filter", gauss_img, 0, 10)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Exercise 7
Use one of your images (or use the car.png image) to try the above filters. Especially, try with large filter kernels (larger than 10) with the median and the Gaussian filter. Remember to transform your image into gray-scale before filtering.

What is the visual difference between in the output? Try to observe places where there is clear light-dark transition.

In [12]:
img_org = cv2.imread("car.png", cv2.IMREAD_GRAYSCALE)

show_in_moved_window("SaltPepper Image", img_org, 0, 10)

for s in [5, 10, 20, 40]:
    size = s
    # Two dimensional filter filled with 1
    weights = np.ones([size, size])
    # Normalize weights
    weights = weights / np.sum(weights)
    res_img = correlate(img_org, weights)
    footprint = np.ones([size, size])
    med_img = median(img_org, footprint)
    gauss_img = gaussian(img_org, sigma)
    pos = int(math.log2(s/5)+1) * 280

    show_in_moved_window('Car Image with Mean Filter {}'.format(size), cv2.resize(res_img, (int(res_img.shape[1]/2), int(res_img.shape[0]/2))), pos, 10)
    show_in_moved_window('Car Image with Median Filter {}'.format(size), cv2.resize(med_img, (int(med_img.shape[1]/2), int(med_img.shape[0]/2))), pos, 200)
    show_in_moved_window("Car Image with Gaussian Filter", cv2.resize(gauss_img, (int(gauss_img.shape[1]/2), int(gauss_img.shape[0]/2))), pos, 400)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Exercise 8
Try to filter the donald_1.png photo with the prewitt_h and prewitt_v filters and show the output without converting the output to unsigned byte. Notice that the output range is [-1, 1]. Try to explain what features of the image that gets high and low values when using the two filters?

In [13]:
from skimage.filters import prewitt_h
from skimage.filters import prewitt_v
from skimage.filters import prewitt

In [14]:
img_org = cv2.imread("donald_1.png", cv2.IMREAD_GRAYSCALE)
img_pre_h = prewitt_h(img_org)
img_pre_v = prewitt_v(img_org)
show_in_moved_window('Donald Image with Prewitt H Filter', img_pre_h, 0, 10)
show_in_moved_window("Donald Image with Prewitt V Filter", img_pre_v, 400, 10)

cv2.waitKey(0)
cv2.destroyAllWindows()